/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planetas;

import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Bataioli
 */
public class Planetas extends javax.swing.JFrame {

    /**
     * Creates new form Planetas
     */
    public Planetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaPrincipal = new javax.swing.JPanel();
        Resultado = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        TituloPesoNaTerra = new javax.swing.JLabel();
        TituloSelecao = new javax.swing.JLabel();
        Mercurio = new javax.swing.JCheckBox();
        Venus = new javax.swing.JCheckBox();
        Marte = new javax.swing.JCheckBox();
        Jupiter = new javax.swing.JCheckBox();
        Saturno = new javax.swing.JCheckBox();
        Urano = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });

        Calcular.setText("Calcular peso");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        TituloPesoNaTerra.setText("Peso na Terra (KG):");

        TituloSelecao.setText("Selecione o Planeta:");

        Mercurio.setText("Mercúrio");
        Mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercurioActionPerformed(evt);
            }
        });

        Venus.setText("Vênus");
        Venus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenusActionPerformed(evt);
            }
        });

        Marte.setText("Marte");

        Jupiter.setText("Júpiter");

        Saturno.setText("Saturno");

        Urano.setText("Urano");

        javax.swing.GroupLayout TelaPrincipalLayout = new javax.swing.GroupLayout(TelaPrincipal);
        TelaPrincipal.setLayout(TelaPrincipalLayout);
        TelaPrincipalLayout.setHorizontalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mercurio)
                            .addComponent(Venus))
                        .addGap(59, 59, 59)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Marte)
                            .addComponent(Jupiter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Urano)
                            .addComponent(Saturno))))
                .addGap(58, 58, 58))
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(TituloSelecao))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(TituloPesoNaTerra)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaPrincipalLayout.setVerticalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TituloPesoNaTerra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(TituloSelecao)
                .addGap(18, 18, 18)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mercurio)
                    .addComponent(Marte)
                    .addComponent(Saturno))
                .addGap(18, 18, 18)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Venus)
                    .addComponent(Jupiter)
                    .addComponent(Urano))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        
    }//GEN-LAST:event_ResultadoActionPerformed

    private void VenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenusActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        
        double pesoTerra = Double.parseDouble(Resultado.getText());
        
        double gravidade = 0;
        String planeta = "";
        
        if (Mercurio.isSelected()) {
            gravidade = 0.37;
            planeta = "Mercurio";
        }else if (Venus.isSelected()){
            gravidade = 0.88;
            planeta = "Venus";
        }else if (Marte.isSelected()){
            gravidade = 0.38;
            planeta = "Marte";
        }else if (Jupiter.isSelected()){
            gravidade = 2.64;
            planeta = "Jupiter";
        }else if (Saturno.isSelected()){
            gravidade = 1.55;
            planeta = "Saturno";
        }else if (Urano.isSelected()){
            gravidade = 1.17;
            planeta = "Urano";
        }else{
            JOptionPane.showMessageDialog(rootPane, "Voce precisa selecionar um planeta");
            return;
        }
        
        double pesoPlaneta = pesoTerra / 10 * gravidade;
        
        JOptionPane.showMessageDialog(rootPane, "Seu peso em "+planeta+" é: "+pesoPlaneta+"KG");
        
        
    }//GEN-LAST:event_CalcularActionPerformed

    private void MercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MercurioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JCheckBox Jupiter;
    private javax.swing.JCheckBox Marte;
    private javax.swing.JCheckBox Mercurio;
    private javax.swing.JTextField Resultado;
    private javax.swing.JCheckBox Saturno;
    private javax.swing.JPanel TelaPrincipal;
    private javax.swing.JLabel TituloPesoNaTerra;
    private javax.swing.JLabel TituloSelecao;
    private javax.swing.JCheckBox Urano;
    private javax.swing.JCheckBox Venus;
    // End of variables declaration//GEN-END:variables
}
